---
type: l3leaf

# L3 Leaf switch group
l3leaf:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: cEOSLab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 2
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.255.1.0/27
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['xdc1-spine-01', 'xdc1-spine-02']
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.0/26
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    #mlag_peer_ipv4_pool: 10.255.1.64/27
    # iBGP Peering between MLAG peers
    #mlag_peer_l3_ipv4_pool: 10.255.1.96/27
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

# If two nodes (and only two) are in the same node_group, they will automatically form an MLAG pair
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    - group: xdc1-leaf-01
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65101
      nodes:
        # Definition of hostnames under the node_group
        - name: xdc1-leaf-01
          id: 1
          mgmt_ip: 192.168.154.13/24
          mgmt_interface: Management0
    - group: xdc1-leaf-02
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65102
      nodes:
        # Definition of hostnames under the node_group
        - name: xdc1-leaf-02
          id: 2
          mgmt_ip: 192.168.154.10/24
          mgmt_interface: Management0
    - group: xdc1-leaf-03
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65103
      nodes:
        # Definition of hostnames under the node_group
        - name: xdc1-leaf-03
          id: 3
          mgmt_ip: 192.168.154.11/24
          mgmt_interface: Management0
    - group: xdc1-leaf-04
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65104
      nodes:
        # Definition of hostnames under the node_group
        - name: xdc1-leaf-04
          id: 4
          mgmt_ip: 192.168.154.14/24
          mgmt_interface: Management0
