name: Execute Provisioning Playbooks

# 1. This tells GitHub the pipeline is triggered manually via an API call
on:
  workflow_dispatch:
    inputs:
      network_data:
        description: 'JSON configuration matrix passed from Flask Web UI'
        required: true

jobs:
  deploy_network:
    # 2. CRITICAL: Tells GitHub to run this job on your local machine's runner
    runs-on: self-hosted  
    
    steps:
      # 3. Pulls down your playbooks and inventory files into the runner workspace
      - name: Checkout Code Base
        uses: actions/checkout@v4

      # 4. Takes the table string from your Flask UI and dumps it into a local file
      - name: Parse Web Data to File
        run: |
          echo '${{ github.event.inputs.network_data }}' > ui_input.json
      - name: test sw connectivity
        run: |
          ping -c 2 192.168.154.2
      #5 update the AVD group var files
      - name: Update AVD Inventory Files
        run: |
          python3 update_inventory.py

      # 6. Executes your first playbook, build configs
      - name: Run Playbook 1 (Build Configuration)
        run: |
          ansible-playbook build.yml -i inventory.yml 

      # 7. Executes your second playbook to push changes to the CVP
      - name: Run Playbook 2 (Deploy Configurations)
        run: |
          ansible-playbook deploy-cvp.yml -i inventory.yml

      # 8. Run ANTA for AVD
      - name: Run ANTA (Deploy Configurations)
        run: |
          ansible-playbook anta.yml -i inventory.yml

      # Run ANTA for additinal tests
      - name: Run ANTA (aditinal tests)
        run: |
          anta nrfu --username admin --password admin --enable --inventory anta_inventory.yml --catalog anta2.yml  md-report --md-output anta2_raport/antaraport.md
